### ISSUE TITLE
DAG生成问题

### ISSUE THREAD

**Issue by 719676340** [linkpark/metarl-offloading#1]
你好  看见/env 中有DAG图的数据   但是想知道DAG图的生成方式   是否可以开源DAG的生成器  非常感谢

**Comment by linkpark** [comment]
> 你好 看见/env 中有DAG图的数据 但是想知道DAG图的生成方式 是否可以开源DAG的生成器 非常感谢

这里是一个开源的dag 生成器 https://github.com/frs69wq/daggen， 另外可能会有更新的，你可以在github上找一下

**Comment by 719676340** [comment]
> > 你好 看见/env 中有DAG图的数据 但是想知道DAG图的生成方式 是否可以开源DAG的生成器 非常感谢
> 
> 这里是一个开源的dag 生成器 [https://github.com/frs69wq/daggen，](https://github.com/frs69wq/daggen%EF%BC%8C) 另外可能会有更新的，你可以在github上找一下

非常感谢

**Comment by linkpark** [comment]
> > > 你好 看见/env 中有DAG图的数据 但是想知道DAG图的生成方式 是否可以开源DAG的生成器 非常感谢
> > 
> > 
> > 这里是一个开源的dag 生成器 [https://github.com/frs69wq/daggen，](https://github.com/frs69wq/daggen%EF%BC%8C) 另外可能会有更新的，你可以在github上找一下
> 
> 非常感谢

不客气哈
